[project]
name = "timegps"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mcp[cli]>=1.13.1",
    "pynmea2>=1.19.0",
    "pyserial>=3.5",
]
